// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB37LQKW6qj5okoC26wzQ8O8pX-jaxAUtk',
    appId: '1:113555503140:web:7174c23b15587af2b480b1',
    messagingSenderId: '113555503140',
    projectId: 'planning-with-ai-f2e38',
    authDomain: 'planning-with-ai-f2e38.firebaseapp.com',
    storageBucket: 'planning-with-ai-f2e38.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBhhkOOQH5tcG1wyoiVgq7SBSbUWvLEIa0',
    appId: '1:113555503140:android:c9b3780b9efcb7ccb480b1',
    messagingSenderId: '113555503140',
    projectId: 'planning-with-ai-f2e38',
    storageBucket: 'planning-with-ai-f2e38.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD6JQMYtiAhcJ3EOmKDr4QGCk7qI2fiC0c',
    appId: '1:113555503140:ios:9f8cc58aa5c4f698b480b1',
    messagingSenderId: '113555503140',
    projectId: 'planning-with-ai-f2e38',
    storageBucket: 'planning-with-ai-f2e38.firebasestorage.app',
    iosBundleId: 'com.example.weatherApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD6JQMYtiAhcJ3EOmKDr4QGCk7qI2fiC0c',
    appId: '1:113555503140:ios:9f8cc58aa5c4f698b480b1',
    messagingSenderId: '113555503140',
    projectId: 'planning-with-ai-f2e38',
    storageBucket: 'planning-with-ai-f2e38.firebasestorage.app',
    iosBundleId: 'com.example.weatherApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB37LQKW6qj5okoC26wzQ8O8pX-jaxAUtk',
    appId: '1:113555503140:web:b8659d595b5f481ab480b1',
    messagingSenderId: '113555503140',
    projectId: 'planning-with-ai-f2e38',
    authDomain: 'planning-with-ai-f2e38.firebaseapp.com',
    storageBucket: 'planning-with-ai-f2e38.firebasestorage.app',
  );
}
